# Generated by Django 5.2.4 on 2025-07-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255)),
                ('sku', models.CharField(help_text='Unique SKU for the product', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available quantity in inventory')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
