# Generated by Django 5.2.4 on 2025-07-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='i_profile',
            field=models.ForeignKey(help_text='User profile that created the product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile'),
        ),
    ]
