# Generated by Django 5.2.4 on 2025-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_i_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Semantic embedding of the product name', null=True),
        ),
    ]
