# Generated by Django 5.2.4 on 2025-07-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity at the time of update')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the stock change')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
