# Generated by Django 5.2.4 on 2025-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
    ]
